server:
  port: 8080

spring:
  application:
    name: msa-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Server
      routes:
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/stores/**,/menus/**
          filters:
            - StripPrefix=1
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when_authorized

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/