server:
  port: 8080

spring:
  application:
    name: msa-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Server
      routes:
        - id: msa-store-service
          uri: lb://MSA-STORE-SERVICE
          predicates:
            - Path=/stores/**
        - id: msa-common-service
          uri: lb://MSA-COMMON-SERVICE
          predicates:
            - Path=/common/**
#          filters:
#            - StripPrefix=1
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when_authorized

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



