server:
  port: 8079

spring:
  application:
   name: msa-common-service
#  datasource:
#    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: Goorm1!!
#  jpa:
#    hibernate:
#      ddl-auto: none           # ?? ? update/validate ?
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.server.mvc: DEBUG
