spring:
  application:
    name: msa-user-service

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!

    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 300000        # testtttt
      max-lifetime: 1500000       # 25md
      keepalive-time: 1200000     # 20mddddd
      connection-timeout: 30000
      validation-timeout: 3000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_UwU3TlTZt



management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
jwt:
  secret: ""
  issuer: ""
  access-token:
    expiration-ms: 900000
  refresh-token:
    expiration-ms: 1209600000

logging:
  level:
    org.springframework.security: INFO
---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


---
spring:
  config:
    activate:
      on-profile: dev
    import: ["aws-secretsmanager:dev"]

  datasource:
    url: jdbc:postgresql://${db_host}:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      enabled: false

server:
    port: 8080


eureka:
    client:
      enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: TRACE