spring:
  application:
    name: msa-user-service

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized
jwt:
  secret: ""
  issuer: ""
  access-token:
    expiration-ms: 900000
  refresh-token:
    expiration-ms: 1209600000

logging:
  level:
    org.springframework.security: INFO
---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://postgres.cpug0kggoegu.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


server:
    port: 8080

eureka:
    client:
      enabled: false

