server:
  port: 8086

spring:
  application:
    name: msa-payment-service
  datasource:
    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

toss:
  api-url: https://api.tosspayments.com
  secret-key: test_sk_GePWvyJnrKblk4AJ4qbEVgLzN97E
  client-key: test_ck_Ba5PzR0Arn9bqEYORBDXVvmYnNeD
