spring:
  application:
    name: msa-payment-service

  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env # 디버깅을 위해 env 추가
  endpoint:
    health:
      show-details: when_authorized
toss:
  api-url: https://api.tosspayments.com
  secret-key: test_sk_GePWvyJnrKblk4AJ4qbEVgLzN97E
  client-key: test_ck_Ba5PzR0Arn9bqEYORBDXVvmYnNeD

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8086
eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://localhost:8761/eureka/

#order:
#  service:
#    url: http://msa-order-service


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://postgres.cpug0kggoegu.ap-northeast-2.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
        enabled: false

server:
  port: 8080

eureka:
   client:
     enabled: false

#order:
#  service:
#    url: http://msa-order-service:8080 # 클라우드 orderservice url