spring:
  application:
   name: msa-store-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://db-goorm1.chqyoqs8q3x4.ap-northeast-2.rds.amazonaws.com/postgres #우리 디비로 바꾸기
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Goorm1!!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      credentials:
        accessKey: AKIAXETF2IMIEZGTIAVC
        secretKey: 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
      s3:
        bucket: groom-team-1-image-bucket
      region:
        static: ap-northeast-2
      stack:
        auto: false
server:
  port: 8081

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.server.mvc: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
    import: ["aws-secretsmanager:dev"]

  datasource:
    url: jdbc:postgresql://${db_host}:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      enabled: false
    aws:
      credentials:
        accessKey: ${credentials_accessKey}
        secretKey: ${credentials_secretKey}
      s3:
        bucket: ${s3_bucket_name}
      region:
        static: ap-northeast-2
      stack:
        auto: false


server:
  port: 8080

eureka:
  client:
    enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO